<?php

namespace AppBundle\Repository;

/**
 * AnswerLinearScaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerLinearScaleRepository extends \Doctrine\ORM\EntityRepository
{
}
