<?php

namespace AppBundle\Repository;

/**
 * AnswerCheckboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerCheckboxRepository extends \Doctrine\ORM\EntityRepository
{
}
