<?php

namespace AppBundle\Repository;

/**
 * AnswerRadioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRadioRepository extends \Doctrine\ORM\EntityRepository
{
}
