<?php

namespace AppBundle\Repository;

/**
 * ChartTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
