# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.poll:
        class: AppBundle\Repository\PollRepository


    app.repository.page:
        class: AppBundle\Repository\PageRepository
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }


    app.pollRepositoryService:
        class: AppBundle\Services\PollRepositoryService
        arguments: ["@doctrine.orm.entity_manager"]
    app.variantRepositoryService:
            class: AppBundle\Services\VariantRepositoryService
            arguments: ["@doctrine.orm.entity_manager"]
    app.apiAuthService:
        class: AppBundle\Services\ApiAuthService
        arguments: ["@request_stack", "%api_token%"]
    app.validationService:
                  class: AppBundle\Services\ValidationService
                  arguments: ["@validator", "@app.variantRepositoryService"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ["@app.helper", "@translator"]
        tags:
          - {name: twig.extension}
    app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments: ["@app.apiAuthService"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    app.helper:
        class: AppBundle\Helper

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
